runserver:
	python3 manage.py runserver

collect_static:
	python3 manage.py collectstatic

make_migrations:
	python3 manage.py makemigrations

migrate:
	python3 manage.py migrate

test:
	python3 manage.py test

all:
	python3 manage.py runserver