FLAGS = python3 manage.py

runserver:
	$(FLAGS) runserver

collectstatic:
	$(FLAGS) collectstatic

makemigrations:
	$(FLAGS) makemigrations

migrate:
	$(FLAGS) migrate

test:
	$(FLAGS) test

all:
	$(FLAGS) runserver