# Generated by Django 3.1.2 on 2021-01-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_two_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resturants',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='resturants',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
